/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/interactions": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.interactions.id"];
          /** The blog post slug. */
          slug?: parameters["rowFilter.interactions.slug"];
          created_at?: parameters["rowFilter.interactions.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["interactions"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** interactions */
          interactions?: definitions["interactions"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.interactions.id"];
          /** The blog post slug. */
          slug?: parameters["rowFilter.interactions.slug"];
          created_at?: parameters["rowFilter.interactions.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.interactions.id"];
          /** The blog post slug. */
          slug?: parameters["rowFilter.interactions.slug"];
          created_at?: parameters["rowFilter.interactions.created_at"];
        };
        body: {
          /** interactions */
          interactions?: definitions["interactions"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** Tracks feedback interactions on my blog. */
  interactions: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    slug: string;
    created_at: string;
    value: boolean;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** interactions */
  "body.interactions": definitions["interactions"];
  "rowFilter.interactions.id": string;
  /** The blog post slug. */
  "rowFilter.interactions.slug": string;
  "rowFilter.interactions.created_at": string;
}

export interface operations {}

export interface external {}
